name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'  # all branches

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      # - name: Install system dependencies
      #   run: sudo apt-get install -y texlive-latex-base texlive-latex-extra context python3-tk
      - name: Test with tox
        run: |
          pip install tox
          tox -- --cov tikzplotly --cov-report xml --cov-report term
      - uses: codecov/codecov-action@v4.0.1
        if: ${{ matrix.python-version == '3.10' && matrix.os == 'ubuntu-latest' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
